// bin2c: writes a binary file as a C++ source defining a byte array.
// SPDX-License-Identifier: Apache-2.0
//
//   whirl-bin2c <input> <output.cpp> <symbol>
// defines `extern const unsigned char <symbol>[]` and
// `extern const unsigned long long <symbol>_size`. The array is 16-byte
// aligned (hipModuleLoadData reads the ELF header in place).

#include <cstdio>
#include <vector>

int main(int argc, char** argv) {
    if (argc != 4) {
        std::fprintf(stderr, "usage: whirl-bin2c <input> <output.cpp> <symbol>\n");
        return 2;
    }
    std::FILE* in = std::fopen(argv[1], "rb");
    if (!in) {
        std::fprintf(stderr, "bin2c: cannot open %s\n", argv[1]);
        return 1;
    }
    std::vector<unsigned char> data;
    unsigned char buf[65536];
    size_t n;
    while ((n = std::fread(buf, 1, sizeof buf, in)) > 0) data.insert(data.end(), buf, buf + n);
    std::fclose(in);

    std::FILE* out = std::fopen(argv[2], "wb");
    if (!out) {
        std::fprintf(stderr, "bin2c: cannot write %s\n", argv[2]);
        return 1;
    }
    std::fprintf(out, "// generated by whirl-bin2c from %s; do not edit\n", argv[1]);
    std::fprintf(out, "extern const unsigned char %s[];\n", argv[3]);
    std::fprintf(out, "extern const unsigned long long %s_size;\n", argv[3]);
    std::fprintf(out, "alignas(16) const unsigned char %s[%zu] = {\n", argv[3], data.size() + 1);
    for (size_t i = 0; i < data.size(); ++i) {
        std::fprintf(out, "%u,", data[i]);
        if (i % 32 == 31) std::fputc('\n', out);
    }
    std::fprintf(out, "0};\n");  // trailing NUL keeps the array non-empty
    std::fprintf(out, "const unsigned long long %s_size = %zuull;\n", argv[3], data.size());
    std::fclose(out);
    return 0;
}
