// The embedded gfx1201 vision code object (generated by cmake/vision.cmake).
// SPDX-License-Identifier: Apache-2.0

#include "whirl/vision.h"

extern const unsigned char whirl_vision_gfx1201[];
extern const unsigned long long whirl_vision_gfx1201_size;

namespace whirl::vision {

std::span<const std::uint8_t> kernelImage() {
    return {whirl_vision_gfx1201, static_cast<std::size_t>(whirl_vision_gfx1201_size)};
}

}  // namespace whirl::vision
